export default function getData() {
    return [{
        id: 1,
        link: "https://static-images.wolke.dev/cool-stuff/burmester-sound-system.png",
    }, {
        id: 2,
        link: "https://static-images.wolke.dev/cool-stuff/gshock-watch.png",
    }, {
        id: 3,
        link: "https://static-images.wolke.dev/cool-stuff/hermes-ash-tray.png",
    }, {
        id: 4,
        link: "https://static-images.wolke.dev/cool-stuff/iwc-yachtclub-watch.png",
    }, {
        id: 5,
        link: "https://static-images.wolke.dev/cool-stuff/llbean-sweater.png",
    }, {
        id: 6,
        link: "https://static-images.wolke.dev/cool-stuff/llbean-zip-sweater.png",
    }, {
        id: 7,
        link: "https://static-images.wolke.dev/cool-stuff/noam-beer.png",
    }, {
        id: 8,
        link: "https://static-images.wolke.dev/cool-stuff/omega-pilot-watch.png",
    }, {
        id: 9,
        link: "https://static-images.wolke.dev/cool-stuff/omega-seamaster-007.png",
    }, {
        id: 10,
        link: "https://static-images.wolke.dev/cool-stuff/omega-speedmaster-olympics.png",
    }, {
        id: 11,
        link: "https://static-images.wolke.dev/cool-stuff/seiko.png",
    }, {
        id: 12,
        link: "https://static-images.wolke.dev/cool-stuff/ysl-digital-watch.png",
    }, {
        id: 13,
        link: "https://static-images.wolke.dev/cool-stuff/birkenstock-clogs.png",
    }, {
        id: 14,
        link: "https://static-images.wolke.dev/cool-stuff/canadagoose-jacket.png",
    }, {
        id: 15,
        link: "https://static-images.wolke.dev/cool-stuff/grau-fire-lamp.png",
    }, {
        id: 16,
        link: "https://static-images.wolke.dev/cool-stuff/hardgraft-geldboerse.png",
    }, {
        id: 17,
        link: "https://static-images.wolke.dev/cool-stuff/llbean-halfzip-fleece.png",
    }, {
        id: 18,
        link: "https://static-images.wolke.dev/cool-stuff/marathon-watch.png",
    }, {
        id: 19,
        link: "https://static-images.wolke.dev/cool-stuff/shackleton-sweater.png",
    }, {
        id: 20,
        link: "https://static-images.wolke.dev/cool-stuff/westleyrichards-cap.png",
    }, {
        id: 21,
        link: "https://static-images.wolke.dev/cool-stuff/wine-glass.png",
    }, {
        id: 22,
        link: "https://static-images.wolke.dev/cool-stuff/leica-camera.png",
    },
    {
        id: 23,
        link: "https://static-images.wolke.dev/cool-stuff/rolex-explorer-2.png",
    }, {
        id: 24,
        link: "https://static-images.wolke.dev/cool-stuff/the-dark-knight-movie.png",
    }, {
        id: 25,
        link: "https://static-images.wolke.dev/cool-stuff/lovefrom-lamp.png",
    }, {
        id: 26,
        link: "https://static-images.wolke.dev/cool-stuff/the-social-network-movie.png",
    }, {
        id: 27,
        link: "https://static-images.wolke.dev/cool-stuff/airpods-pro-3.png",
    }, {
        id: 28,
        link: "https://static-images.wolke.dev/cool-stuff/bleu-de-chanel.png",
    }, {
        id: 29,
        link: "https://static-images.wolke.dev/cool-stuff/blitzscaling.png",
    }, {
        id: 30,
        link: "https://static-images.wolke.dev/cool-stuff/deep-folio-hardgraft.png",
    }, {
        id: 31,
        link: "https://static-images.wolke.dev/cool-stuff/dior-homme-intense.png",
    }, {
        id: 32,
        link: "https://static-images.wolke.dev/cool-stuff/la-marzoco-linea-mini.png",
    }, {
        id: 33,
        link: "https://static-images.wolke.dev/cool-stuff/maison-margiella-gats.png",
    }, {
        id: 34,
        link: "https://static-images.wolke.dev/cool-stuff/napa-leder-massimodutti-tasche.png",
    }, {
        id: 35,
        link: "https://static-images.wolke.dev/cool-stuff/why-does-the-stock-market-go-up.png",
    }];
}